package de.muenchen.oss.sonar.backend.abrechnung;

public enum ZustellungsbevollmaechtigterTyp {

    GESETZLICHER_VERTRETER,
    VORMUND,
    BETREUER,
    NACHLASSVERWALTER,
    NACHLASSPFLEGER,
    TESTAMENTSVOLLSTRECKER,
    ZWANGSVERWALTER,
    PFLEGER,
    VORSTAND,
    GESCHAEFTSFUEHRENDER_GESELLSCHAFTER,
    LIQUIDATOR,
    KONKURSVERWALTER,
    STEUERLICHER_VERTRETER,
    EMPFANGSBEVOLLMAECHTIGTER,
    VERGLEICHSVERWALTER,
    GESAMTRECHTSNACHFOLGER,
    VERWALTER_NACH_DEM_WEG,
    GESCHAEFTSFUEHRER,
    GESELLSCHAFTER,
    INSOLVENZVERWALTER,
    NACHTRAGSLIQUIDATOR,
    TREUHAENDER,
    VORLAEUFIGER_INSOLVENZVERWALTER

}
